name: "box"

createVisualShape:
  shapeType: "GEOM_BOX"
  halfExtents: [0.2, 0.2, 0.2]


createCollisionShape:
  shapeType: "GEOM_BOX"
  halfExtents: [0.2, 0.2, 0.2]

changeDynamics:
  lateralFriction: 1.0
  spinningFriction: 0.0
  rollingFriction: 0.0
  restitution: 0.0
  linearDamping: 0.04
  angularDamping: 0.04
  contactStiffness: 2000.0
  contactDamping: 0.7


object_tf:
  offset:
    transform: [0.5, 0., 0.]
