name: "kuka_lbr"

loadURDF:
  fileName: "{rpbi_examples}/robots/med7.urdf"
  useFixedBase: 1
  basePosition: [0.5, 0., 0.]

initial_revolute_joint_positions_are_deg: true
is_visual_robot: false

setJointMotorControlArray:
  controlMode: "POSITION_CONTROL"

publish_joint_state_frequency: 30

broadcast_link_states: true
brodcast_link_states_frequency: 30
