name: "tom"

loadURDF:
  fileName: "{rpbi_examples}/robots/example.urdf"
  useFixedBase: 1
  basePosition: [0, 0, 0]

initial_joint_position:
  joint1: 0.0

initial_revolute_joint_positions_are_deg: false
is_visual_robot: false

setJointMotorControlArray:
  controlMode: "POSITION_CONTROL"

publish_joint_state_frequency: 30

broadcast_link_states: true
brodcast_link_states_frequency: 30
