name: "nextage"
urdf_filename: "{nextagea_description}/urdf/NextageAOpen.urdf"
tf_frame_id: "nextage_base"
init_position: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 15.0, -10.0, 0.0, -20.0, 0.0]
alpha: 1
