name: "nextage"
# urdf_filename: "{nextagea_description}/urdf/NextageAOpen.urdf"
urdf_filename: "{nextage_smart_factory}/urdf/nextagea_dual_pick.urdf"
# tf_frame_id: "sim/nextage_base"
tf_frame_id: "nextage_base"
init_position: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 15.0, -10.0, 0.0, -20.0, 90.0]
alpha: 1
