name: "pushing_box"
base_mass: 1
init_position: [0.48, -0.25, 0.73]
init_base_orient_eulerXYZ: [0, 0, 0]
init_linear_velocity: [0, 0, 0]
init_angular_velocity: [0, 0, 0]
object_type: 'box'
half_extends: [0.09, 0.198, 0.065]
rgba_color: [0.1, 0.54, 0.8, 0.3]
lateral_friction: 0.2
spinning_friction: 0.0
rolling_friction: 0.0
restitution: 0.0
linear_damping: 0.
angular_damping: 0.
contact_stiffness: 10000.0
contact_damping: 0.7
tf_frame_id: "rpbi_work/nextage_sliding_box_visual"
