#
# Configuration file for tracking using sliding
# 

contactMode: 'sliding_cc_slack'  # 'sticking', 'sliding_cc', or 'sliding_mi'
solverName: 'knitro'  # 'ipopt', 'snopt', 'gurobi', 'qpoases', 'knitro'
# solverName: 'ipopt'  # 'ipopt', 'snopt', 'gurobi', 'qpoases', 'knitro'
# W_x: [1.0, 1.0, 0.008, 0.]  # diagonal state weights
W_x: [0.1, 0.1, 0.1, 0.]  # diagonal state weights
W_u: [0., 0., 0., 0.]  # diagonal control weights
# W_u: [0.01, 0.01, 0.001, 0.001]  # diagonal control weights
K_goal: 100
# X_goal: [0.80, -0.15, 0., 0.]
# X_goal: [0.80, -0.05, 0., 0.]
# X_goal: [0.80, -0.25, 0., 0.]
# X_goal: [0.4, 0.23, 0., 0.]  # old
# X_goal: [0.80, 0.20, 0., 0.]  # temp forward
X_goal: [0.4, 0.27, 0., 0.]  # temp reorient
numObs: 0
linDynFlag: False
# codeGenFlag: True
codeGenFlag: False
noPrintingFlag: False
phases: null
TimeHorizon: 3 # time horizon
# TimeHorizon: 12 # time horizon
