camera_distance: 1.0
camera_yaw: -40
camera_pitch: -40.0
camera_target_position: [0.5, 0, 0.2]
configure_camera_from_ros: False
gravity: [0, 0, -9.807]
pybullet_sampling_frequency: 250
enable_real_time_simulation: True
