estimation:
  conditionPos: -0.35 #0.25 #0.15 # simulation
  conditionVel: 0.05 # simulation
  uncertainty: 0.10
  # uncertainty: 0.12

object:
  finObjPos: [-0.25, 2.2, 1.5, 0, 0, 0]
#  finObjPos: [0.2, 0.0, 1.4, 3.14, 0, 0]
  maxObjPos: [10, 10, 10, 10, 10, 10]
  finObjVel: [0., 0., 0., 0., 0., 0.]
  maxObjVel: [10, 10, 10, 10, 10, 10]
  slackObjPos: [0.2, 2.2, 0.1, 3.14, 3.14, 3.14]
  slackObjVel: [0.01, 0.01, 0.01, 0.01, 0.01, 0.01]
  # reducedNode: 23 # 25 #40 #37
  reducedNode: 27 #26 #27 # 35 #37


robotYin:
  workspace: 1.4
  minWorkspace: [-1.4, -0.75, 0.4]
  maxWorkspace: [1.4, 0.3, 0.85]

  # minWorkspace: [-1.4, -0.75, 0.2]
  # maxWorkspace: [1.4, 0.3, 0.85]

robotYang:
  workspace: 1.4
  minWorkspace: [-1.4, -0.65, 0.4]
  maxWorkspace: [1.4, 0.3, 0.85]

  # minWorkspace: [-1.4, -0.75, 0.4]
  # maxWorkspace: [1.4, 0.3, 0.85]
