#
# Configuration file for tracking using sliding
# 

xLenght: 0.09 # [meter]
yLenght: 0.198 # [meter]
pusherRadious: 0.013 #  [meter]
pusherFricCoef: 0.15
pusherForceLim:  0.6
pusherAngleVelLim: 4.0
Kz_max: 50
Kz_min: 0.1
