#
# Configuration file for tracking using sliding
# 

xLenght: 0.09 # [meter]
yLenght: 0.198 # [meter]
pusherRadious: 0.015 #  [meter]
pusherFricCoef: 0.2
pusherForceLim:  0.6
pusherAngleVelLim: 5.0
Kz_max: 50
Kz_min: 0.1
