#
# Configuration file for tracking using sliding
# 
contactMode: 'sliding_cc_slack'  # 'sticking', 'sliding_cc', 'sliding_cc_slack', or 'sliding_mi'
solverName: 'knitro'  # 'ipopt', 'snopt', 'gurobi', 'qpoases', 'knitro'
W_x: [1.0, 1.0, 0.01, 0.001]  # diagonal state weights
W_u: [0.01, 0.01, 0.0002, 0.0002]  # diagonal control weights
K_goal: 10
X_goal: null
numObs: 1
linDynFlag: False
codeGenFlag: False
noPrintingFlag: True
phases: null
