name: "pushing_box"

createVisualShape:
  shapeType: "GEOM_BOX"
  halfExtents: [0.1, 0.1, 0.075]
  rgbaColor: [0.9, 1.0, 0.3, 1.0]

createCollisionShape:
  shapeType: "GEOM_BOX"
  halfExtents: [0.1, 0.1, 0.075]

baseMass: 1.0
basePosition: [-0.6, 0.0, 0.3]

changeDynamics:
  lateralFriction: 1.0
  spinningFriction: 0.0
  rollingFriction: 0.0
  restitution: 0.0
  linearDamping: 0.04
  angularDamping: 0.04
  contactStiffness: 2000.0
  contactDamping: 0.7
