#
# Basic example
#


#
# Pybullet instance
#
connect:
  connection_mode: 'GUI'

setGravity:
  gravX: 0.0
  gravY: 0.0
  gravZ: -9.81

timeStep: 0.01
start_pybullet_after_initialization: true
status_hz: 50


#
# Pybullet visualizer
#
configureDebugVisualizer:
  enable: 0
  flag: 'COV_ENABLE_GUI'

resetDebugVisualizerCamera:
  cameraDistance: 2.0
  cameraYaw: 135
  cameraPitch: -30.0
  cameraTargetPosition: [0.0, 0.0, 0.75]


#
# Pybullet objects
#

robots:
  # - "{rpbi_examples}/configs/run_pose/talos.yaml"
  # - "{rpbi_examples}/configs/run_pose/kuka_lwr.yaml"
  # - "{rpbi_examples}/configs/run_pose/human_model.yaml"
  - "{rpbi_examples}/configs/run_pose/kinova.yaml"  

collision_objects:
  - "{rpbi_examples}/configs/floor.yaml"

visual_objects:
  - "{rpbi_examples}/configs/run_pose/table.yaml"  

urdfs:
  - "{rpbi_examples}/configs/run_pose/cup.yaml"
  # - "{rpbi_examples}/configs/run_pose/mug.yaml"    
