#
# Basic example
#


#
# Pybullet instance
#
connect:
  connection_mode: 'GUI'
  # options: "--mp4=$HOME/fig8.mp4"

setGravity:
  gravX: 0.0
  gravY: 0.0
  gravZ: -9.81

timeStep: 0.01
start_pybullet_after_initialization: true
status_hz: 50


#
# Pybullet visualizer
#
configureDebugVisualizer:
  enable: 0
  flag: 'COV_ENABLE_GUI'

resetDebugVisualizerCamera:
  cameraDistance: 2.0
  cameraYaw: 0.0
  cameraPitch: -45.0
  cameraTargetPosition: [0.0, 0.0, 0.0]


#
# Pybullet objects
#
collision_objects:
  - "{rpbi_examples}/configs/floor.yaml"
robots:
  - "{rpbi_examples}/configs/run_kuka/kuka_lwr_0.yaml"
  - "{rpbi_examples}/configs/run_kuka/kuka_lwr_1.yaml"
