name: "kuka_lwr_0"

loadURDF:
  fileName: "{rpbi_examples}/robots/kuka_lwr.urdf"
  basePosition: [0, 1, 0]
  useFixedBase: 1

initial_joint_position:
  lwr_arm_0_joint: 0.0
  lwr_arm_1_joint: 30.0
  lwr_arm_2_joint: 0.0
  lwr_arm_3_joint: -90.0
  lwr_arm_4_joint: 0.0
  lwr_arm_5_joint: 60.0
  lwr_arm_6_joint: 0.0

initial_revolute_joint_positions_are_deg: true
is_visual_robot: false

setJointMotorControlArray:
  controlMode: "POSITION_CONTROL"

publish_joint_state_frequency: 30

broadcast_link_states: true
brodcast_link_states_frequency: 30
