name: "dynamic_box"

createVisualShape:
  shapeType: "GEOM_BOX"
  halfExtents: [0.3, 0.15, 0.1]
  rgbaColor: [0.9, 1.0, 0.3, 1.0]

createCollisionShape:
  shapeType: "GEOM_BOX"
  halfExtents: [0.3, 0.15, 0.1]

baseMass: 0.5
basePosition: [0.0, 0.0, 1.0]

resetBaseVelocity:
  linearVelocity: [0.0, 0, 1.5]

changeDynamics:
  lateralFriction: 1.0
  spinningFriction: 0.0
  rollingFriction: 0.0
  restitution: 0.0
  linearDamping: 0.04
  angularDamping: 0.04
  contactStiffness: 2000.0
  contactDamping: 0.7
